#pragma once
#include <unordered_map>
#include <unordered_set>
#include <string>

const char STOP_MARKER = '*';
const std::unordered_map<std::string, char> CodonTable ({
	{ "UUU", 'F' },
	{ "CUU", 'L' },
	{ "AUU", 'I' },
	{ "GUU", 'V' },
	{ "UUC", 'F' },
	{ "CUC", 'L' },
	{ "AUC", 'I' },
	{ "GUC", 'V' },
	{ "UUA", 'L' },
	{ "CUA", 'L' },
	{ "AUA", 'I' },
	{ "GUA", 'V' },
	{ "UUG", 'L' },
	{ "CUG", 'L' },
	{ "AUG", 'M' },
	{ "GUG", 'V' },
	{ "UCU", 'S' },
	{ "CCU", 'P' },
	{ "ACU", 'T' },
	{ "GCU", 'A' },
	{ "UCC", 'S' },
	{ "CCC", 'P' },
	{ "ACC", 'T' },
	{ "GCC", 'A' },
	{ "UCA", 'S' },
	{ "CCA", 'P' },
	{ "ACA", 'T' },
	{ "GCA", 'A' },
	{ "UCG", 'S' },
	{ "CCG", 'P' },
	{ "ACG", 'T' },
	{ "GCG", 'A' },
	{ "UAU", 'Y' },
	{ "CAU", 'H' },
	{ "AAU", 'N' },
	{ "GAU", 'D' },
	{ "UAC", 'Y' },
	{ "CAC", 'H' },
	{ "AAC", 'N' },
	{ "GAC", 'D' },
	{ "CAA", 'Q' },
	{ "AAA", 'K' },
	{ "GAA", 'E' },
	{ "CAG", 'Q' },
	{ "AAG", 'K' },
	{ "GAG", 'E' },
	{ "UGU", 'C' },
	{ "CGU", 'R' },
	{ "AGU", 'S' },
	{ "GGU", 'G' },
	{ "UGC", 'C' },
	{ "CGC", 'R' },
	{ "AGC", 'S' },
	{ "GGC", 'G' },
	{ "CGA", 'R' },
	{ "AGA", 'R' },
	{ "GGA", 'G' },
	{ "UGG", 'W' },
	{ "CGG", 'R' },
	{ "AGG", 'R' },
	{ "GGG", 'G' },
    {"UGA", STOP_MARKER},
    {"UAG", STOP_MARKER},
    {"UAA", STOP_MARKER},
});

const std::unordered_map<char, std::vector<std::string>> ReverseCodonTable{
        { 'H', {"CAC", "CAU"}},
        { 'K', {"AAG", "AAA"}},
        { 'S', {"UCC", "UCG", "UCU", "UCA", "AGU", "AGC"}},
        { 'F', {"UUU", "UUC"}},
        { 'V', {"GUC", "GUG", "GUU", "GUA"}},
        { 'I', {"AUC", "AUU", "AUA"}},
        { 'A', {"GCU", "GCC", "GCA", "GCG"}},
        { 'G', {"GGC", "GGU", "GGG", "GGA"}},
        { 'D', {"GAU", "GAC"}},
        { 'L', {"CUU", "CUC", "UUA", "CUA", "UUG", "CUG"}},
        { 'Q', {"CAG", "CAA"}},
        { 'T', {"ACA", "ACG", "ACU", "ACC"}},
        { 'M', {"AUG"}},
        { 'E', {"GAA", "GAG"}},
        { 'P', {"CCG", "CCA", "CCU", "CCC"}},
        { 'N', {"AAU", "AAC"}},
        { 'Y', {"UAU", "UAC"}},
        { 'C', {"UGU", "UGC"}},
        { 'R', {"CGU", "AGG", "CGC", "CGA", "AGA", "CGG"}},
        { 'W', {"UGG"}},
        { STOP_MARKER, {"UAG", "UAA", "UGA"}},
};